spring.application.name=marketplace
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Chicha@2840@
spring.jpa.hibernate.ddl-auto =create
